const menu = [
  {
    id: 1,
    title: "Ultimate Burger Steak",
    category: "breakfast",
    price: 150.99,
    img: "./newimages/item-1.png",
    desc: `1 pc Ultimate Burger Steak with Egg and Fries and 1 large Coca-Cola `,
  },
  {
    id: 2,
    title: "Super Meal B",
    category: "lunch",
    price: 135.99,
    img: "./newimages/item-2.png",
    desc: `1-pc. Chickenjoy w Burger Steak & Half Jolly Spaghetti Super Meal`,
  },
  {
    id: 3,
    title: "ChickenJoy Bucket and Palabok Family Plan",
    category: "dinner",
    price: 699.99,
    img: "./newimages/item-3.png",
    desc: `6 pcs Jolibee Chickenjoy with 1pc Palabok Family Plan topped with Eggs `,
  },
  {
    id: 4,
    title: "Breakfast Hotdog",
    category: "breakfast",
    price: 80.99,
    img: "./newimages/item-4.png",
    desc: `1pc Hotdog with Rice and Egg with a choice of Fresh Hot Coffee or Tea`,
  },
  {
    id: 5,
    title: "Chickenjoy w Crisscut Fries",
    category: "lunch",
    price: 130.99,
    img: "./newimages/item-5.png",
    desc: `1pc Chickenjoy with Crisscut Fries & 1pc Rice with a Drink of your choice `,
  },
  {
    id: 6,
    title: "Chickenjoy with Palabok",
    category: "dinner",
    price: 180.99,
    img: "./newimages/item-6.png",
    desc: `1pc Chickenjoy with Palabok topped in egg with a Drink of your choice`,
  },
  {
    id: 7,
    title: "Breakfast Shanghai",
    category: "breakfast",
    price: 120.99,
    img: "./newimages/item-7.png",
    desc: `4pc Jolibee Shanghai with Rice and Egg with a choice of Hot Coffee or Tea `,
  },
  {
    id: 8,
    title: "Cheesy Deluxe Yumburger",
    category: "lunch",
    price: 220.99,
    img: "./newimages/item-8.png",
    desc: `Cheesy Deluxe Yumburger with Fries and a Drink of your choice Value Meal`,
  },
  {
    id: 9,
    title: "Chickenjoy with Spaghetti and Drink",
    category: "dinner",
    price: 150.99,
    img: "./newimages/item-9.png",
    desc: `1 pc Jolibee Chickenhoy with Rice and Spaghetti with a Drink of your choice`,
  },
];
export default menu;
